version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "postgres"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  userservice:
    image: userapp/user-service:0.0.1-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      DB_PASSWORD: "postgres"
      DB_USER: "postgres"
    networks:
      - backend
networks:
  backend:
    driver: bridge
